### ISSUE TITLE
Cannot properly add filled buckets as fuel for furnaces. (Crafttweaker related)

### ISSUE THREAD

**Issue by justinrusso** [TheCyberBrick/The-Betweenlands#555]
#### Betweenlands version:

3.3.4

#### Forge version:

14.23.2.2641

#### Singleplayer or Multiplayer:

Singleplayer

#### Installed mods:

https://minecraft.curseforge.com/projects/sevtech-ages

#### How to reproduce:

Trying to use a filled bucket as a fuel in a furnace causes it to add incorrectly. Instead of it being the bucket with the liquid, it is the empty bucket.

#### Expected result:

The fuel is set to the bucket with liquid.
![image](https://user-images.githubusercontent.com/25138621/38175375-796b68b2-35a9-11e8-859f-dcf000684178.png)

#### Actual result:

The fuel is an empty bucket.
![image](https://user-images.githubusercontent.com/25138621/38175378-824f7482-35a9-11e8-93e6-4313c5d4abef.png)

#### Crafttweaker Script:
```
furnace.setFuel(<ceramics:clay_bucket>.withTag({fluids: {FluidName: "gasoline", Amount: 1000}}), 75000);
furnace.setFuel(<forge:bucketfilled>.withTag({FluidName: "gasoline", Amount: 1000}), 75000);
furnace.setFuel(<thebetweenlands:bl_bucket:1>.withTag({Fluid: {FluidName: "gasoline", Amount: 1000}}), 75000);
furnace.setFuel(<thebetweenlands:bl_bucket>.withTag({Fluid: {FluidName: "gasoline", Amount: 1000}}), 75000);
```

#### References: 
https://github.com/Darkosto/SevTech-Ages/issues/1191

**Comment by GoryMoon** [comment]
This is solved with 75975b3.
The only issue is that you can't look at the usages in SevTech but it works fine to lookup the usages in Dev and running separate.

**Comment by justinrusso** [comment]
Odd... Well, since I'm using all buckets for that, I'm not too concerned that the 2 buckets dont show. Thanks!

**Comment by justinrusso** [comment]
This seems to still be an issue.

I just tested it now on 3.3.6 and although the bucket doesn't show a use like it used to, it still gets used as fuel.

**Comment by justinrusso** [comment]
Oh I see.. do buckets now have an empty tag when empty?
Seems like pre-existing empty buckets work, but once they get used once and taken out it changes its tag

**Comment by GoryMoon** [comment]
Yeah, they need that empty tag when being compared if they can be used as fuel, if it's missing the nbt it won't be required in the comparison
